[build]
  publish = "public"
  command = "yarn build"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[headers]]
  for = "https://keen-sammet-6a7c61.netlify.app/*"
  [headers.values]
    X-Robots-Tag = "noindex"