[build]
  publish = "public"
  command = "yarn build"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "noindex"